// Package banner renders the Chore Crusher ASCII art banner for use as the
// TUI title and CLI startup splash. The figlet text is shared across all
// three repos; only the color gradient differs, sourced from that repo's
// active appstyles.Theme.
package banner

import (
	"strings"

	"charm.land/lipgloss/v2"

	"github.com/filipemolina/chore-crusher/src/appstyles"
)

// figletText is the pre-rendered ASCII art for "Chore Crusher" (font: slant).
// Generated by pyfiglet; stored as Go string literals to avoid a runtime
// dependency on an external font file.
var figletLines = []string{
	"   ________                       ______                __             ",
	"  / ____/ /_  ____  ________     / ____/______  _______/ /_  ___  _____",
	" / /   / __ \\/ __ \\/ ___/ _ \\   / /   / ___/ / / / ___/ __ \\/ _ \\/ ___/",
	"/ /___/ / / / /_/ / /  /  __/  / /___/ /  / /_/ (__  ) / / /  __/ /    ",
	"\\____/_/ /_/\\____/_/   \\___/   \\____/_/   \\__,_/____/_/ /_/\\___/_/",
}

// Banner renders the figlet banner with a horizontal gradient from the
// theme's Accent color to its StatusInProgress color, applied per-line
// using lipgloss truecolor. The background is the theme's BackgroundPanel.
//
// Each line of the figlet gets a color interpolated along the gradient,
// creating a smooth left-to-right color sweep across the text.
func Banner(t appstyles.Theme) string {
	cols := lipgloss.Blend1D(len(figletLines), t.Accent, t.StatusInProgress)
	var sb strings.Builder
	for i, line := range figletLines {
		fg := cols[i]
		style := lipgloss.NewStyle().Foreground(fg)
		sb.WriteString(style.Render(line))
		if i < len(figletLines)-1 {
			sb.WriteByte('\n')
		}
	}
	return sb.String()
}
