-- 0002_agent_activity.sql — per-entity "an agent is working on this" claim.
--
-- One row per entity (a task or a list). An agent claims an entity to tell
-- the TUI to show a live spinner on it; the claim expires after WorkTTL
-- seconds of inactivity so a dead agent's spinner does not linger
-- (docs/DESIGN.md §7: the TUI polls and reads this like every other write).
CREATE TABLE IF NOT EXISTS AgentActivity (
    id            text primary key,        -- ULID, generated by store.NewID
    entity_type   text not null,           -- 'task' | 'list'
    entity_id     text not null,           -- the Task.id or List.id the agent is on
    agent_id      text not null,           -- a short label the caller chose
    kind          text not null default 'working', -- 'working' | 'inspecting'
    acquired_at   integer not null,        -- unix seconds; renewed when a claim is made
    UNIQUE(entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_activity_entity
    ON AgentActivity(entity_type, entity_id);
