-- 0003_list_owner.sql — declared owner tag of a list ("pi", "claude", ...).
-- Empty = owned by nobody: every agent may read it and update task
-- status/progress only; structural writes are refused for all agents until a
-- human tags it (rename to "<tag>: <name>", backfilled on next open) or an
-- agent recreates the work under its own tag.
-- Populated by the MCP add_list tool (defaults to the server identity) and by
-- GetOrCreateAgentList; the backfill that adopts the "<tag>:" name convention
-- lands in Step B.
-- Idempotent: the migration runner records version 3 in schema_migrations and
-- never re-applies it.
ALTER TABLE List ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
